<div class="info-set">
    <h2 class="legend">Shipping Method</h2>
<form method="post" action="<?php echo $this->getUrl('apruvepayment/payment/updateShippingMethod');?>">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <script type="text/javascript">
        //<![CDATA[
        //var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <button type="submit" class="button"><span><span>Update</span></span></button>
</form>
</div>