<?php
$helper = Mage::helper('apruvepayment');
$paymentRequestModel = $helper->getPaymentRequestApiModel();
?>

<div id="apruveDiv" style="display: inline-block;"></div>

<script type="test/javascript">
    var sh = '<?php echo $paymentRequestModel->getSecureHash();?>';
    var pr = <?php echo $paymentRequestModel->getPaymentRequestJSON();?>;
    var updatedShippingUrl = '<?php echo $helper->getAjaxAddressUpdatedUrl() ?>'
    var oApruvePayment = new ApruvePayment(sh, pr, updatedShippingUrl);
</script>